"""Application URL routes for public pages, orders, profiles and admin tools."""

from django.conf import settings
from django.urls import path
from .views import (
    about_view,
    contacts_view,
    create_admin,
    create_order,
    create_product,
    delete_admin,
    delete_order,
    detail_order,
    dismiss_track_notice,
    dispatch_orders_view,
    exchange_rates_view,
    export_orders_excel,
    export_profile_orders_excel,
    faq_view,
    hidden_entrypoint,
    import_orders_excel,
    import_profile_orders_excel,
    index,
    login_view,
    logout_view,
    my_profile_redirect,
    order_list,
    panel_entrypoint,
    print_receipt,
    profile_view,
    order_total_preview,
    print_settlement_sheet,
    track_center_view,
    set_language_view,
    toggle_status,
    change_order,
)

urlpatterns = [
    path('', index, name='index'),
    path('about/', about_view, name='about'),
    path('faq/', faq_view, name='faq'),
    path('contacts/', contacts_view, name='contacts'),
    path('lang/<str:lang_code>/', set_language_view, name='set_language'),
    path('api/exchange-rates/', exchange_rates_view, name='exchange_rates_api'),
    path('create/product/', create_product, name='create_product'),
    path('create/order/', create_order, name='create_order'),
    path('order/', order_list, name='orders'),
    path('tracks/', track_center_view, name='track_center'),
    path('order/calc-total/', order_total_preview, name='order_total_preview'),
    path('order/export/excel/', export_orders_excel, name='orders_export_excel'),
    path('order/import/excel/', import_orders_excel, name='orders_import_excel'),
    path('order/dispatch/', dispatch_orders_view, name='dispatch_orders'),
    path('order/<slug:slug>/change/', change_order, name='change_order'),
    path('order/<slug:slug>/delete/', delete_order, name='delete_order'),
    path('order/<slug:slug>/detail/', detail_order, name='detail_order'),
    path('order/<slug:slug>/receipt/', print_receipt, name='print_receipt'),
    path('order/<slug:slug>/settlement/', print_settlement_sheet, name='print_settlement_sheet'),
    path('notifications/track-reminder/dismiss/', dismiss_track_notice, name='dismiss_track_notice'),

    path('toggle_status/<int:user_id>/', toggle_status, name='toggle_status'),
    path('delete_admin/<int:user_id>/', delete_admin, name='delete_admin'),
    path('create/admin/', create_admin, name='create_admin'),
    path('profile/', my_profile_redirect, name='my_profile'),
    path('profile/<str:user>/export/excel/', export_profile_orders_excel, name='profile_export_excel'),
    path('profile/<str:user>/import/excel/', import_profile_orders_excel, name='profile_import_excel'),
    path('profile/<str:user>/', profile_view, name='profile'),
    path(settings.STAFF_LOGIN_URL, login_view, name='staff_login'),
    path(settings.STAFF_LOGIN_URL.rstrip('/'), login_view, name='staff_login_no_slash'),
    path('panel/', panel_entrypoint, name='panel'),
    path('panel', panel_entrypoint, name='panel_no_slash'),
    path('login/', hidden_entrypoint, name='login'),
    path('logout/', logout_view, name='logout'),
]
