# Generated by Django 5.0.3 on 2024-03-23 02:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Mahsulot Nomi')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Mahsulot Soni')),
                ('product_price_currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RMB', 'RMB')], default='UZS', max_length=3, verbose_name='Mahsulot Valyutasi')),
                ('product_price', models.DecimalField(decimal_places=3, default='0.1', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Mahsulot Narxi')),
                ('store', models.CharField(choices=[('None', 'None'), ('Taoboa', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('1688', '1688')], default='None', max_length=10, verbose_name='Mahsulot Do`koni')),
                ('link', models.URLField(blank=True, max_length=1500, null=True, verbose_name='Mahsulot Linki')),
                ('image1', models.ImageField(default='product.png', upload_to='products/images/', verbose_name='Mahsulot Rasmi #1')),
                ('image2', models.ImageField(default='product.png', upload_to='products/images/', verbose_name='Mahsulot Rasmi #2')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='O`zgartirilgan Sana')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('receipt_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1500)])),
                ('first_name', models.CharField(max_length=100, verbose_name='Mijoz Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Mijoz Familiyasi')),
                ('phone1', models.PositiveIntegerField(blank=True, default=999999999, null=True, validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Raqam #1')),
                ('phone2', models.PositiveIntegerField(blank=True, default=999999999, null=True, validators=[django.core.validators.MaxValueValidator(9)], verbose_name='Raqam #2')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Qarz')),
                ('description', models.TextField(max_length=500, verbose_name='Tarif')),
                ('status', models.CharField(choices=[('none', 'None'), ('start', 'Berildi'), ('continue', 'Tranzit'), ('end', 'Keldi'), ('force', 'Otmen')], default='none', max_length=8, verbose_name='Status')),
                ('come', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Kelgan Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='O`zgartirilgan Sana')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akmalexpress.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgs', models.DecimalField(decimal_places=3, default=0.5, max_digits=5, verbose_name='Og`irlig')),
                ('cargo', models.DecimalField(decimal_places=3, default=9, max_digits=7, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='O`zgartirilgan Sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akmalexpress.product')),
            ],
        ),
    ]
