# Generated by Django 6.0.3 on 2026-03-17 11:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('receipt_number', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1500)], verbose_name='Kvitansiya Raqam')),
                ('order_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Sana')),
                ('shipping_method', models.CharField(choices=[('AVIA', 'АВИА'), ('iPost', 'iPost'), ('17994', '17994')], default='AVIA', max_length=8, verbose_name='Yuborish turi')),
                ('track_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Mijoz Ismi')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Mijoz Familiyasi')),
                ('phone1', models.PositiveBigIntegerField(blank=True, db_index=True, default=999999999, null=True, verbose_name='Raqam #1')),
                ('phone2', models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='Raqam #2')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Qarz')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс')),
                ('cargo_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cargo')),
                ('cargo_enabled', models.BooleanField(default=True, verbose_name='Cargo yoqilgan')),
                ('service_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Xizmat')),
                ('manual_total', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Итог вручную')),
                ('service_enabled', models.BooleanField(default=True, verbose_name='Xizmat yoqilgan')),
                ('usd_rate', models.DecimalField(decimal_places=2, default=12205, max_digits=17, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='USD kursi')),
                ('rmb_rate', models.DecimalField(decimal_places=2, default=1807, max_digits=17, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='RMB kursi')),
                ('description', models.TextField(blank=True, default='', max_length=500, verbose_name='Tarif')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('ordered', 'Заказан'), ('transit', 'В пути'), ('arrived', 'Прибыл'), ('cancelled', 'Отмена')], default='accepted', max_length=16, verbose_name='Status')),
                ('come', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Kelgan Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='O`zgartirilgan Sana')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='akmalexpress.order')),
            ],
            options={
                'verbose_name': 'Вложение заказа',
                'verbose_name_plural': 'Вложения заказов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=140, verbose_name='Название товара')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product_price_currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RMB', 'RMB')], default='UZS', max_length=3)),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('shipping_method', models.CharField(choices=[('AVIA', 'АВИА'), ('iPost', 'iPost'), ('17994', '17994')], default='AVIA', max_length=8, verbose_name='Тип доставки')),
                ('track_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Трек-номер')),
                ('store', models.CharField(choices=[('None', 'None'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688'), ('95', '95'), ('MadeChina', 'Made in China')], default='None', max_length=10)),
                ('link', models.URLField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='akmalexpress.order')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=100, verbose_name='Mahsulot Nomi')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Mahsulot Soni')),
                ('product_price_currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RMB', 'RMB')], default='UZS', max_length=3, verbose_name='Mahsulot Valyutasi')),
                ('product_price', models.DecimalField(decimal_places=3, default='0.1', max_digits=18, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Mahsulot Narxi')),
                ('store', models.CharField(choices=[('None', 'None'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688'), ('95', '95'), ('MadeChina', 'Made in China')], default='None', max_length=10, verbose_name='Mahsulot Do`koni')),
                ('link', models.URLField(blank=True, max_length=1500, null=True, verbose_name='Mahsulot Linki')),
                ('image1', models.ImageField(default='product.png', upload_to='products/images/', verbose_name='Mahsulot Rasmi #1')),
                ('image2', models.ImageField(default='product.png', upload_to='products/images/', verbose_name='Mahsulot Rasmi #2')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='O`zgartirilgan Sana')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akmalexpress.product'),
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgs', models.DecimalField(decimal_places=3, default=0.5, max_digits=5, verbose_name='Og`irlig')),
                ('cargo', models.DecimalField(decimal_places=3, default=9, max_digits=7, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='O`zgartirilgan Sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akmalexpress.product')),
            ],
            options={
                'verbose_name': 'Деталь товара',
                'verbose_name_plural': 'Детали товаров',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user_id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'order_date'], name='order_status_date_idx'),
        ),
    ]
