# Generated by Django 6.0.3 on 2026-03-23 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_number',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kvitansiya Raqam'),
        ),
    ]
