# Generated by Django 5.0.3 on 2024-03-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mijoz Familiyasi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone1',
            field=models.PositiveIntegerField(blank=True, default=999999999, null=True, verbose_name='Raqam #1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.PositiveIntegerField(blank=True, default=999999999, null=True, verbose_name='Raqam #2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('start', 'Начат'), ('continue', 'В пути'), ('end', 'Пришел'), ('force', 'Отменен')], default='none', max_length=8, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
    ]
