# Generated by Django 5.0.3 on 2024-03-24 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0002_order_track_number_alter_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.PositiveIntegerField(blank=True, default='', null=True, verbose_name='Raqam #2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1500)], verbose_name='Kvitansiya Raqam'),
        ),
    ]
