# Generated by Django 6.0.3 on 2026-03-23 09:42

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0002_alter_order_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='come',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Kelgan Sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Yaratilgan Sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='Raqam #2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('ordered', 'Заказан'), ('transit', 'В пути'), ('arrived', 'Прибыл'), ('cancelled', 'Отмена')], db_index=True, default='accepted', max_length=16, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'order_date'], name='order_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date', 'created_at'], name='order_date_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'come'], name='order_status_come_idx'),
        ),
    ]
