# Generated by Django 5.0.3 on 2024-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0003_alter_order_description_alter_order_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
