# Generated by Django 6.0.3 on 2026-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0003_alter_order_come_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('AVIA', 'АВИА'), ('iPost', 'iPost'), ('17994', '17994'), ('UZPOST', 'UzPost'), ('UZUM', 'Uzum'), ('MEEST', 'Meest'), ('GLOBBING', 'Globbing'), ('RUSPOST', 'Почта России')], default='AVIA', max_length=8, verbose_name='Yuborish turi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_method',
            field=models.CharField(choices=[('AVIA', 'АВИА'), ('iPost', 'iPost'), ('17994', '17994'), ('UZPOST', 'UzPost'), ('UZUM', 'Uzum'), ('MEEST', 'Meest'), ('GLOBBING', 'Globbing'), ('RUSPOST', 'Почта России')], default='AVIA', max_length=8, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store',
            field=models.CharField(choices=[('None', 'None'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688'), ('95', '95'), ('MadeChina', 'Made in China'), ('Amazon', 'Amazon'), ('eBay', 'eBay'), ('America', 'Америка'), ('China', 'Китай'), ('Russia', 'Россия')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('None', 'None'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688'), ('95', '95'), ('MadeChina', 'Made in China'), ('Amazon', 'Amazon'), ('eBay', 'eBay'), ('America', 'Америка'), ('China', 'Китай'), ('Russia', 'Россия')], default='None', max_length=10, verbose_name='Mahsulot Do`koni'),
        ),
    ]
