# Generated by Django 6.0.3 on 2026-03-05 05:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0004_alter_order_description_alter_order_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Xizmat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('None', 'None'), ('Taoboa', 'Taobao'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688')], default='None', max_length=10, verbose_name='Mahsulot Do`koni'),
        ),
    ]
