# Generated by Django 6.0.3 on 2026-03-05 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0006_alter_order_phone1_alter_order_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='akmalexpress.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140, verbose_name='Название товара')),
                ('product_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product_price_currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RMB', 'RMB')], default='UZS', max_length=3)),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('store', models.CharField(choices=[('None', 'None'), ('Taoboa', 'Taobao'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688')], default='None', max_length=10)),
                ('link', models.URLField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='akmalexpress.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
