# Generated by Django 6.0.3 on 2026-03-05 10:24

from django.db import migrations, models


def normalize_store_values(apps, schema_editor):
    Product = apps.get_model('akmalexpress', 'Product')
    OrderItem = apps.get_model('akmalexpress', 'OrderItem')

    Product.objects.filter(store='Taoboa').update(store='Taobao')
    OrderItem.objects.filter(store='Taoboa').update(store='Taobao')
    Product.objects.filter(store='95madecn').update(store='MadeChina')
    OrderItem.objects.filter(store='95madecn').update(store='MadeChina')


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0007_orderattachment_orderitem'),
    ]

    operations = [
        migrations.RunPython(normalize_store_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderitem',
            name='store',
            field=models.CharField(choices=[('None', 'None'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688'), ('95', '95'), ('MadeChina', 'Made in China')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('None', 'None'), ('Taobao', 'Taobao'), ('Alibaba', 'Alibaba'), ('AliExpress', 'AliExpress'), ('Pinduoduo', 'Pinduoduo'), ('Poizon', 'Poizon'), ('1688', '1688'), ('95', '95'), ('MadeChina', 'Made in China')], default='None', max_length=10, verbose_name='Mahsulot Do`koni'),
        ),
    ]
