# Generated by Django 6.0.3 on 2026-03-09 05:44

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    Order = apps.get_model('akmalexpress', 'Order')
    mapping = {
        'none': 'accepted',
        'start': 'ordered',
        'continue': 'transit',
        'end': 'arrived',
        'force': 'cancelled',
    }
    for old_value, new_value in mapping.items():
        Order.objects.filter(status=old_value).update(status=new_value)


def rollback_statuses(apps, schema_editor):
    Order = apps.get_model('akmalexpress', 'Order')
    reverse_mapping = {
        'accepted': 'none',
        'ordered': 'start',
        'transit': 'continue',
        'arrived': 'end',
        'cancelled': 'force',
    }
    for new_value, old_value in reverse_mapping.items():
        Order.objects.filter(status=new_value).update(status=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0008_alter_orderitem_store_alter_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('AVIA', 'АВИА'), ('iPost', 'iPost'), ('17994', '17994')], default='AVIA', max_length=8, verbose_name='Yuborish turi'),
        ),
        migrations.RunPython(migrate_old_statuses, rollback_statuses),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('ordered', 'Заказан'), ('transit', 'В пути'), ('arrived', 'Прибыл'), ('cancelled', 'Отмена')], default='accepted', max_length=16, verbose_name='Status'),
        ),
    ]
