# Generated by Django 6.0.3 on 2026-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0009_order_shipping_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_enabled',
            field=models.BooleanField(default=True, verbose_name='Cargo yoqilgan'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_enabled',
            field=models.BooleanField(default=True, verbose_name='Xizmat yoqilgan'),
        ),
    ]
