# Generated by Django 6.0.3 on 2026-03-09 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmalexpress', '0010_order_cargo_enabled_order_service_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rmb_rate',
            field=models.DecimalField(decimal_places=2, default=1807, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='RMB kursi'),
        ),
        migrations.AddField(
            model_name='order',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=12205, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='USD kursi'),
        ),
    ]
